---
version: "3"

vars:
  BREWFILE: "{{.ROOT_DIR}}/taskfiles/brew/Brewfile"

tasks:
  install:
    desc: Install tools required for 'k8s-on-macos' project with Brew
    cmd: brew bundle --file {{.BREWFILE}}
    preconditions:
      - { msg: "Missing Homebrew", sh: "command -v brew" }
      - { msg: "Missing Brewfile", sh: "test -f {{.BREWFILE}}" }