---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../cp-init-base

patches:
- path: InitConfiguration.yaml
  target:
    group: kubeadm.k8s.io
    version: v1beta4
    kind: InitConfiguration
    name: kubeadm-init-initconfig
- path: ClusterConfiguration.yaml
  target:
    group: kubeadm.k8s.io
    version: v1beta4
    kind: ClusterConfiguration
    name: kubeadm-init-clusterconfig
