apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-selfsigned
  namespace: cert-manager
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: root-ca
  duration: 2160h
  renewBefore: 1800h
  commonName: Selfsigned root CA
  subject:
    organizations:
    - Kubernetes
    organizationalUnits:
    - Sandbox
  dnsNames:
  - sandbox.k8s.internal
  issuerRef:
    name: root-ca-selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca
spec:
  ca:
    secretName: root-ca
