---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - httproute.yaml
configMapGenerator:
  - name: flux-operator-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml