---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    semver: v0.8.x
  ignore: |-
    # exclude all
    /*
    # except helm chart directory
    !/charts/metrics-server/
  interval: 15m