apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app application
  namespace: &ns namespace
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: app-values
  interval: 1h
